export const FERTILIZER_LIST_REQUEST='FERTILIZER_LIST_REQUEST';
export const FERTILIZER_LIST_SUCCESS='FERTILIZER_LIST_SUCCESS';
export const FERTILIZER_LIST_FAILS='FERTILIZER_LIST_FAILS';


export const FERTILIZER_DETAILS_REQUEST='FERTILIZER_DETAILS_REQUEST';
export const FERTILIZER_DETAILS_SUCCESS='FERTILIZER_DETAILS_SUCCESS';
export const FERTILIZER_DETAILS_FAILS='FERTILIZER_DETAILS_FAILS';