export const RENTING_LIST_REQUEST='RENTING_LIST_REQUEST';
export const RENTING_LIST_SUCCESS='RENTING_LIST_SUCCESS';
export const RENTING_LIST_FAILS='RENTING_LIST_FAILS';


export const RENTING_DETAILS_REQUEST='RENTING_DETAILS_REQUEST';
export const RENTING_DETAILS_SUCCESS='RENTING_DETAILS_SUCCESS';
export const RENTING_DETAILS_FAILS='RENTING_DETAILS_FAILS';