export const SEED_LIST_REQUEST='SEED_LIST_REQUEST';
export const SEED_LIST_SUCCESS='SEED_LIST_SUCCESS';
export const SEED_LIST_FAILS='SEED_LIST_FAILS';


export const SEED_DETAILS_REQUEST='SEED_DETAILS_REQUEST';
export const SEED_DETAILS_SUCCESS='SEED_DETAILS_SUCCESS';
export const SEED_DETAILS_FAILS='SEED_DETAILS_FAILS';